### ISSUE TITLE
Conflict in requirements.txt 

### ISSUE THREAD

**Issue by billabongrob** [akebrissman/raspberry-kiosk#1]
ERROR: Cannot install -r requirements.txt (line 1) and ansible-base==2.10.7 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested ansible-base==2.10.7
    ansible 3.4.0 depends on ansible-base<2.11 and >=2.10.9

**Comment by akebrissman** [comment]
Thanks for reporting this. 
Issue solved.
